name: rest-api

services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: praneeth
      POSTGRES_PASSWORD: bat2001
      POSTGRES_DB: students
    ports:
      - "5433:5432"
    volumes:
      - api_pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL : postgres://praneeth:bat2001@db:5432/students
    depends_on:
        - db
volumes:
  api_pgdata: