name: rest-api

services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: praneeth
      POSTGRES_PASSWORD: bat2001
      POSTGRES_DB: students
    ports:
      - "5433:5432"
    volumes:
      - api_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U","praneeth"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://praneeth:bat2001@db:5432/students
    depends_on:
      db:
        condition: service_healthy

volumes:
  api_pgdata: