name: rest-api

services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5433:5432"
    volumes:
      - api_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U","praneeth","-d","students"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://$DATABASE_USER:$DATABASE_PASSWORD@db:5432/$DATABASE_NAME
    depends_on:
      db:
        condition: service_healthy

volumes:
  api_pgdata: