name: rest-api

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL : postgres://praneeth:bat2001@db:5432/students
    depends_on:
        - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: praneeth
      POSTGRES_PASSWORD: bat2001
      POSTGRES_DB: students
    ports:
      - "5433:5432"
